version: 2
updates:
  - package-ecosystem: cargo
    directory: .
    schedule:
      interval: weekly
    groups:
      all-rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: cellnoor-ui
    schedule:
      interval: weekly
    groups:
      all-typescript-dependencies:
        patterns:
          - "*"
