repos:
  - repo: local
    hooks:
      - id: lint_rust
        name: Lint Rust
        entry: ./scripts/pre-commit/lint_rust.sh
        language: script
        pass_filenames: false

      - id: lint_cellnoor-ui
        name: Lint cellnoor-ui
        entry: ./scripts/pre-commit/lint_cellnoor-ui.sh
        language: script
        pass_filenames: false

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.5.0
    hooks:
      - id: sqlfluff-lint
        exclude: ^db/migrations/00000000000000_diesel_initial_setup/down\.sql|migrations/0009_library-type-specification/up\.sql$
      - id: sqlfluff-fix
        exclude: ^db/migrations/00000000000000_diesel_initial_setup/down\.sql|migrations/0009_library-type-specification/up\.sql$

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
      - id: taplo-lint
