name: Check TypeScript Code
on:
  push:
    paths:
      - cellnoor-ui/**

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        working-directory: cellnoor-ui
        run: bun install

      - name: Lint
        working-directory: cellnoor-ui
        run: bun run --bun check

      - name: Test
        working-directory: cellnoor-ui
        run: bun test

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2

      - name: Format
        run: deno fmt --check --unstable-component cellnoor-ui
